### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by MehdiSheykhveysi** [Ali-YousefiTelori/BinaryGo#1]
What Is Nuget Command For Install That?

**Comment by Ali-YousefiTelori** [comment]
Hello Mahdi and thank you for your issue,
JsonGo is in Test level,  I will add into nuget package manager after tests done.

**Comment by Ali-YousefiTelori** [comment]
@MehdiSheykhveysi JsonGo Preview1 Published on nuget today, you can install it from [here](https://www.nuget.org/packages/JsonGo/).
