### ISSUE TITLE
System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.

### ISSUE THREAD

**Issue by MagicAndre1981** [Ali-YousefiTelori/BinaryGo#3]
When I try to serialize an object I get the following exception:

```
System.ArgumentException: Cannot bind to the target method because its signature or security transparency is not compatible with that of the delegate type.

at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
at JsonGo.Runtime.TypeGoInfo.GetDelegateInstance(Type type, PropertyInfo propertyInfo)
at JsonGo.Runtime.TypeGoInfo.Generate(Type type)
at JsonGo.Runtime.TypeGoInfo.Generate(Type type)
at JsonGo.Runtime.TypeGoInfo.Generate(Type type)
at JsonGo.Serializer.SerializeObject(Object& data, TypeGoInfo& typeGoInfo)
at JsonGo.Serializer.Serialize(Object data)
```

**Comment by Ali-YousefiTelori** [comment]
Thank you for your issue, can you show me an example to test and fix this problem?

**Comment by MagicAndre1981** [comment]
I'm on vacation and don't want to debug issues in my freetime.

**Comment by Ali-YousefiTelori** [comment]
It's ok if you had free time tell me the example i will find and fix the bug.Thank you

**Comment by MagicAndre1981** [comment]
I 've created a small EF6 demo some time and tried to serialize the data I get here.

I use the Employee database of firebird3 (`"C:\Program Files\Firebird\Firebird_3_0\examples\empbuild\EMPLOYEE.FDB"`)

**Comment by Ali-YousefiTelori** [comment]
I published new version of JsonGo in [Nuget ](https://www.nuget.org/packages/JsonGo/) it will throw user friendly exception for your types, pls check and show me the exception throw we will see the type and property name.

**Comment by MagicAndre1981** [comment]
Here is what I get:

`System.Exception: 'Cannot create delegate for property HasValue in type System.Nullable1[[System.Int16, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'`

**Comment by Ali-YousefiTelori** [comment]
Bug fixed and Preview4 published on [Nuget](https://www.nuget.org/packages/JsonGo/)

**Comment by MagicAndre1981** [comment]
thanks, tested it and now get a new error:

```
System.Exception
  HResult=0x80131500
  Message=Cannot create delegate for property EMP_NO in type EMPLOYEE
  Source=JsonGo
  StackTrace:
   at JsonGo.Runtime.TypeGoInfo.Generate(Type type) 
   at JsonGo.Serializer.SerializeObject(Object& data, TypeGoInfo& typeGoInfo) 
   at JsonGo.Serializer.Serialize(Object data)

Inner Exception 1:
ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: method
```

declaration was auto generated by EF tool in VS2017 when reverse engineer the model from database:

```
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.None)]
public short EMP_NO { get; set; }
```

**Comment by Ali-YousefiTelori** [comment]
I published preview5 please check it if you had time.

**Comment by MagicAndre1981** [comment]
Serializering works, but for [deserialize data I have a new issue](https://github.com/Ali-YousefiTelori/JsonGo/issues/7)
